- name: install mysqld
  apt: 
    name: mysql-server
    state: present

- name: copy mysqld.cnf
  copy:
    src: roles/mysql/files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql

- name: start mysql
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: create wordpress_db
  mysql_db:
    name: wordpress_db
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    

- name: create mysql user
  mysql_user:
    name: menta
    password: menta123
    host: localhost
    priv: '*.*:ALL'
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

