- name: Download Zabbix package
  get_url:
    url: "https://repo.zabbix.com/zabbix/5.0/ubuntu-arm64/pool/main/z/zabbix-release/zabbix-release_latest_5.0+ubuntu20.04_all.deb"
    dest: "/tmp/zabbix-release_latest_5.0+ubuntu20.04_all.deb"

- name: Install Zabbix release package
  apt:
    deb: "/tmp/zabbix-release_latest_5.0+ubuntu20.04_all.deb"

- name: Install Zabbix components
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-agent
      - pip
    state: present
    update_cache: yes


- name: Check if Zabbix database is already initialized
  mysql_query:
    login_user: zabbix
    login_password: "{{ lookup('env', 'ZABBIX_DB_PASSWORD') }}"
    login_db: zabbix
    query: "SHOW TABLES LIKE 'users';"
  register: db_check

- name: Import Zabbix database schema using zcat
  shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -u zabbix -p"{{ lookup('env', 'ZABBIX_DB_PASSWORD') }}" zabbix
  args:
    executable: /bin/bash
  when: db_check.query_result[0] | length == 0

- name: Set global log_bin_trust_function_creators to 0
  mysql_query:
    query: "SET GLOBAL log_bin_trust_function_creators = 0"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: copy zabbox_server.conf
  copy:
    src: roles/zabbix-server/files/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- name: Start required services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - zabbix-server
    - zabbix-agent

- name: Set Python 3 interpreter for this role
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: install zabbix-api
  pip:
    name: zabbix-api
    state: present
    executable: pip3    



